import { Action } from './types';

const examples: Action[][] = [
  [
    { name: 'A', time: 3, predecessors: [] },
    { name: 'B', time: 2, predecessors: ['A'] },
    { name: 'C', time: 5, predecessors: ['A'] },
    { name: 'D', time: 4, predecessors: ['B', 'C'] },
    { name: 'E', time: 2, predecessors: ['D'] },
    { name: 'F', time: 3, predecessors: ['D'] },
    { name: 'G', time: 2, predecessors: ['E', 'F'] },
    { name: 'H', time: 1, predecessors: ['G'] },
  ],
  [
    { name: 'A', time: 3, predecessors: [] },
    { name: 'B', time: 4, predecessors: ['A'] },
    { name: 'C', time: 6, predecessors: ['A'] },
    { name: 'D', time: 7, predecessors: ['B'] },
    { name: 'E', time: 1, predecessors: ['D'] },
    { name: 'F', time: 2, predecessors: ['C'] },
    { name: 'G', time: 3, predecessors: ['C'] },
    { name: 'H', time: 4, predecessors: ['G'] },
    { name: 'I', time: 1, predecessors: ['E', 'F', 'H'] },
    { name: 'J', time: 2, predecessors: ['I'] },
  ],
  [
    { name: 'A', time: 5, predecessors: [] },
    { name: 'B', time: 7, predecessors: [] },
    { name: 'C', time: 6, predecessors: ['A'] },
    { name: 'D', time: 8, predecessors: ['A'] },
    { name: 'E', time: 3, predecessors: ['B'] },
    { name: 'F', time: 4, predecessors: ['C'] },
    { name: 'G', time: 2, predecessors: ['C'] },
    { name: 'H', time: 5, predecessors: ['E', 'D', 'F'] },
  ],
];

export const results: Action[][] = [
  [
    {
      name: 'A',
      time: 3,
      predecessors: [],
      ES: 0,
      EF: 3,
      LF: 3,
      LS: 0,
      slack: 0,
      critical: true,
    },
    {
      name: 'B',
      time: 2,
      predecessors: [
        'A',
      ],
      ES: 3,
      EF: 5,
      LF: 8,
      LS: 6,
      slack: 3,
      critical: false,
    },
    {
      name: 'C',
      time: 5,
      predecessors: [
        'A',
      ],
      ES: 3,
      EF: 8,
      LF: 8,
      LS: 3,
      slack: 0,
      critical: true,
    },
    {
      name: 'D',
      time: 4,
      predecessors: [
        'B',
        'C',
      ],
      ES: 8,
      EF: 12,
      LF: 12,
      LS: 8,
      slack: 0,
      critical: true,
    },
    {
      name: 'E',
      time: 2,
      predecessors: [
        'D',
      ],
      ES: 12,
      EF: 14,
      LF: 15,
      LS: 13,
      slack: 1,
      critical: false,
    },
    {
      name: 'F',
      time: 3,
      predecessors: [
        'D',
      ],
      ES: 12,
      EF: 15,
      LF: 15,
      LS: 12,
      slack: 0,
      critical: true,
    },
    {
      name: 'G',
      time: 2,
      predecessors: [
        'E',
        'F',
      ],
      ES: 15,
      EF: 17,
      LF: 17,
      LS: 15,
      slack: 0,
      critical: true,
    },
    {
      name: 'H',
      time: 1,
      predecessors: [
        'G',
      ],
      ES: 17,
      EF: 18,
      LF: 18,
      LS: 17,
      slack: 0,
      critical: true,
    },
  ],
  [
    {
      name: 'A',
      time: 3,
      predecessors: [],
      ES: 0,
      EF: 3,
      LF: 3,
      LS: 0,
      slack: 0,
      critical: true,
    },
    {
      name: 'B',
      time: 4,
      predecessors: [
        'A',
      ],
      ES: 3,
      EF: 7,
      LF: 8,
      LS: 4,
      slack: 1,
      critical: false,
    },
    {
      name: 'C',
      time: 6,
      predecessors: [
        'A',
      ],
      ES: 3,
      EF: 9,
      LF: 9,
      LS: 3,
      slack: 0,
      critical: true,
    },
    {
      name: 'D',
      time: 7,
      predecessors: [
        'B',
      ],
      ES: 7,
      EF: 14,
      LF: 15,
      LS: 8,
      slack: 1,
      critical: false,
    },
    {
      name: 'E',
      time: 1,
      predecessors: [
        'D',
      ],
      ES: 14,
      EF: 15,
      LF: 16,
      LS: 15,
      slack: 1,
      critical: false,
    },
    {
      name: 'F',
      time: 2,
      predecessors: [
        'C',
      ],
      ES: 9,
      EF: 11,
      LF: 16,
      LS: 14,
      slack: 5,
      critical: false,
    },
    {
      name: 'G',
      time: 3,
      predecessors: [
        'C',
      ],
      ES: 9,
      EF: 12,
      LF: 12,
      LS: 9,
      slack: 0,
      critical: true,
    },
    {
      name: 'H',
      time: 4,
      predecessors: [
        'G',
      ],
      ES: 12,
      EF: 16,
      LF: 16,
      LS: 12,
      slack: 0,
      critical: true,
    },
    {
      name: 'I',
      time: 1,
      predecessors: [
        'E',
        'F',
        'H',
      ],
      ES: 16,
      EF: 17,
      LF: 17,
      LS: 16,
      slack: 0,
      critical: true,
    },
    {
      name: 'J',
      time: 2,
      predecessors: [
        'I',
      ],
      ES: 17,
      EF: 19,
      LF: 19,
      LS: 17,
      slack: 0,
      critical: true,
    },
  ],
  [
    {
      name: 'A',
      time: 5,
      predecessors: [],
      ES: 0,
      EF: 5,
      LF: 5,
      LS: 0,
      slack: 0,
      critical: true,
    },
    {
      name: 'B',
      time: 7,
      predecessors: [],
      ES: 0,
      EF: 7,
      LF: 12,
      LS: 5,
      slack: 5,
      critical: false,
    },
    {
      name: 'C',
      time: 6,
      predecessors: [
        'A',
      ],
      ES: 5,
      EF: 11,
      LF: 11,
      LS: 5,
      slack: 0,
      critical: true,
    },
    {
      name: 'D',
      time: 8,
      predecessors: [
        'A',
      ],
      ES: 5,
      EF: 13,
      LF: 15,
      LS: 7,
      slack: 2,
      critical: false,
    },
    {
      name: 'E',
      time: 3,
      predecessors: [
        'B',
      ],
      ES: 7,
      EF: 10,
      LF: 15,
      LS: 12,
      slack: 5,
      critical: false,
    },
    {
      name: 'F',
      time: 4,
      predecessors: [
        'C',
      ],
      ES: 11,
      EF: 15,
      LF: 15,
      LS: 11,
      slack: 0,
      critical: true,
    },
    {
      name: 'G',
      time: 2,
      predecessors: [
        'C',
      ],
      ES: 11,
      EF: 13,
      LF: 20,
      LS: 18,
      slack: 7,
      critical: false,
    },
    {
      name: 'H',
      time: 5,
      predecessors: [
        'E',
        'D',
        'F',
      ],
      ES: 15,
      EF: 20,
      LF: 20,
      LS: 15,
      slack: 0,
      critical: true,
    },
  ],
];

export default examples;
